#!/bin/env bash
X=$1
Y=$2
if [[ -n $1 ]]; then
    X=$1
else
    echo -e "\e[1mno flags specified\e[0m"
    exit 0
fi
if [[ -n $2 ]]; then
    Y=$2
else
    echo -e "\e[1m1 out of 2 flags specified\e[0m"
    exit 0
fi
if ((Y < 1)); then
    Y=1
fi
for ((i=0; i<=$X; i++)); do
	echo "------"
    echo 'clicked'
    xdotool click 1
    sleep $Y
done
